name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1

      - name: Vet Go code
        run: go vet ./...

      - name: Test Go code
        run: go test -v -race ./...

      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD
